In [87]:
# !pip install pandas

### Series Object in One Dimensional Array

In [88]:
import pandas as pd

#using a list

s1 = pd.Series([1,2,3,4,5]) #list of values with labels attached to it

s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [89]:
# custom index

s2 = pd.Series([1,2,3,4,5], index = ['a','b','c','d','e'])

s2

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [90]:
# using a dictionary

s3 = pd.Series({
    'Name':'Ashuka',
    'Roll No':8,
    'Address': 'Naya Thimi',
    'Gender': 'Female'
})

s3

Name           Ashuka
Roll No             8
Address    Naya Thimi
Gender         Female
dtype: object

In [91]:
# changing the position of an index

s4 = pd.Series({
    'a':1,
    'b':2,
    'c':3
},index = ['b','d','a','c'])

s4

b    2.0
d    NaN
a    1.0
c    3.0
dtype: float64

#### Accessing Values

In [92]:
s5 = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])

s5

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [93]:
print(s5[0])

print()
print(s5[2:5])

# print(s5[-1]) -> Error

print()
print(s5['a'])

1

c    3
d    4
e    5
dtype: int64

1

C:\Users\Dell\AppData\Local\Temp\ipykernel_23256\1526698644.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s5[0])

In [94]:
# using .iloc and .loc

#iloc -> access by number position

print(s5.iloc[0])
print()
print(s5.iloc[0:2])
print()
print(s5.iloc[-1])

1

a    1
b    2
dtype: int64

5

In [95]:
#loc -> access by label/index name

print(s5.loc['a'])
print()
print(s5.loc['a':'d'])
print()
print(s5.loc['d':'a':-1])

1

a    1
b    2
c    3
d    4
dtype: int64

d    4
c    3
b    2
a    1
dtype: int64

#### Useful Operations

In [96]:
a1 = pd.Series([1,2,3,4,50])
a2 = pd.Series([11,12,31,41,5])

a1 + a2

0    12
1    14
2    34
3    45
4    55
dtype: int64

In [97]:
a1 * a2

0     11
1     24
2     93
3    164
4    250
dtype: int64

In [98]:
a1 / a2

0     0.090909
1     0.166667
2     0.096774
3     0.097561
4    10.000000
dtype: float64

In [99]:
a1 % a2

0    1
1    2
2    3
3    4
4    0
dtype: int64

### Creating a Dataframe

In [100]:
# from a dictionary

df = pd.DataFrame(
    {
        'Name':['Ashuka','Bini','Thomas','Simran','Thomas','Dipesh'],
        'Address':['Naya Thimi','Dudhpati','Koteshwor','Pepsicola','Koteshwor','Baneshwor'],
        'Age':[20,19,18,19,18,22],
        'Marks':[90,91,88,91,88,97]
    })

df

     Name     Address  Age  Marks
0  Ashuka  Naya Thimi   20     90
1    Bini    Dudhpati   19     91
2  Thomas   Koteshwor   18     88
3  Simran   Pepsicola   19     91
4  Thomas   Koteshwor   18     88
5  Dipesh   Baneshwor   22     97

In [101]:
df.to_excel('Student_Details.xlsx',index = False) #converts to an excel file

In [102]:
df.to_csv('Student_Details.csv',index = False) #converts to a csv file

In [103]:
df.head() #gives first 5 values

     Name     Address  Age  Marks
0  Ashuka  Naya Thimi   20     90
1    Bini    Dudhpati   19     91
2  Thomas   Koteshwor   18     88
3  Simran   Pepsicola   19     91
4  Thomas   Koteshwor   18     88

In [104]:
df.tail() #gives last 5 values

     Name    Address  Age  Marks
1    Bini   Dudhpati   19     91
2  Thomas  Koteshwor   18     88
3  Simran  Pepsicola   19     91
4  Thomas  Koteshwor   18     88
5  Dipesh  Baneshwor   22     97

In [105]:
df['Name'] #extracting columns

0    Ashuka
1      Bini
2    Thomas
3    Simran
4    Thomas
5    Dipesh
Name: Name, dtype: object

In [106]:
df[['Name','Address']] # extracting multiple columns

     Name     Address
0  Ashuka  Naya Thimi
1    Bini    Dudhpati
2  Thomas   Koteshwor
3  Simran   Pepsicola
4  Thomas   Koteshwor
5  Dipesh   Baneshwor

In [107]:
df.columns

Index(['Name', 'Address', 'Age', 'Marks'], dtype='object')

In [108]:
df.columns.to_list()

['Name', 'Address', 'Age', 'Marks']

In [109]:
list(df.columns)

['Name', 'Address', 'Age', 'Marks']

In [110]:
df.shape

(6, 4)

In [111]:
df[df['Address'] == 'Naya Thimi']

     Name     Address  Age  Marks
0  Ashuka  Naya Thimi   20     90

In [112]:
df[['Name','Address']][df['Address'] == 'Naya Thimi']

     Name     Address
0  Ashuka  Naya Thimi

In [113]:
df[(df['Address'] == 'Naya Thimi') & (df['Age']>=20)]

     Name     Address  Age  Marks
0  Ashuka  Naya Thimi   20     90

In [114]:
df[['Name','Age']][(df['Address'] == 'Naya Thimi') & (df['Age']>=20)]

     Name  Age
0  Ashuka   20

In [115]:
df.describe()

             Age      Marks
count   6.000000   6.000000
mean   19.333333  90.833333
std     1.505545   3.311596
min    18.000000  88.000000
25%    18.250000  88.500000
50%    19.000000  90.500000
75%    19.750000  91.000000
max    22.000000  97.000000

In [116]:
df.describe(include = 'all') 

#count-> No of not-null values
#unique -> No. of unique values
#top-> The most frequent value (if equal, then the top most value gets displayed)
#freq-> How many times the top value appears
#NaN-> Missing value / empty cell

          Name    Address        Age      Marks
count        6          6   6.000000   6.000000
unique       5          5        NaN        NaN
top     Thomas  Koteshwor        NaN        NaN
freq         2          2        NaN        NaN
mean       NaN        NaN  19.333333  90.833333
std        NaN        NaN   1.505545   3.311596
min        NaN        NaN  18.000000  88.000000
25%        NaN        NaN  18.250000  88.500000
50%        NaN        NaN  19.000000  90.500000
75%        NaN        NaN  19.750000  91.000000
max        NaN        NaN  22.000000  97.000000

In [117]:
print(f'The memory consumed by the data is: {df.memory_usage(deep = True)/1024} KB')
print(f'The total memory consumed by the data is: {df.memory_usage(deep = True).sum()/1024} KB')

The memory consumed by the data is: Index      0.128906
Name       0.320312
Address    0.339844
Age        0.046875
Marks      0.046875
dtype: float64 KB
The total memory consumed by the data is: 0.8828125 KB

In [118]:
df.dtypes #object means text/strings

Name       object
Address    object
Age         int64
Marks       int64
dtype: object

In [119]:
categorical_columns = df.select_dtypes(include = ['object','category']).columns

#category -> special pandas dtype for columns with limited repeated values like Yes/No, Male/Female

In [120]:
categorical_columns

Index(['Name', 'Address'], dtype='object')

In [121]:
df[categorical_columns]

     Name     Address
0  Ashuka  Naya Thimi
1    Bini    Dudhpati
2  Thomas   Koteshwor
3  Simran   Pepsicola
4  Thomas   Koteshwor
5  Dipesh   Baneshwor

In [122]:
numerical_columns = df.select_dtypes(exclude = ['object','category']).columns

In [123]:
numerical_columns

Index(['Age', 'Marks'], dtype='object')

In [124]:
df[numerical_columns]

   Age  Marks
0   20     90
1   19     91
2   18     88
3   19     91
4   18     88
5   22     97

In [125]:
numerical_columns1 = df.select_dtypes(include = ['int64','float64','number']).columns

#number automatically covers int64, float64, and all other numeric types, no need to write them separately

In [126]:
numerical_columns1

Index(['Age', 'Marks'], dtype='object')

##### Index(['Age', 'Marks'], dtype='object') 
##### Here, dtype='object' is talking about the names themselves (which are strings), NOT the data inside those columns.

In [127]:
import numpy as np

num_cols = df.select_dtypes(include = np.number).columns

In [128]:
df[num_cols]

   Age  Marks
0   20     90
1   19     91
2   18     88
3   19     91
4   18     88
5   22     97

In [129]:
df.info()  # gives you a quick full summary of your entire DataFrame in one go

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     6 non-null      object
 1   Address  6 non-null      object
 2   Age      6 non-null      int64
 3   Marks    6 non-null      int64
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

In [130]:
df.isnull() #gives True when the values are missing, else False

    Name  Address    Age  Marks
0  False    False  False  False
1  False    False  False  False
2  False    False  False  False
3  False    False  False  False
4  False    False  False  False
5  False    False  False  False

In [131]:
df.isnull().sum()

Name       0
Address    0
Age        0
Marks      0
dtype: int64

In [132]:
df1 = pd.read_csv('Student_Details.csv') 
df1

     Name     Address  Age  Marks
0  Ashuka  Naya Thimi   20     90
1    Bini    Dudhpati   19     91
2  Thomas   Koteshwor   18     88
3  Simran   Pepsicola   19     91
4  Thomas   Koteshwor   18     88
5  Dipesh   Baneshwor   22     97

In [133]:
df1.isnull().sum()

Name       0
Address    0
Age        0
Marks      0
dtype: int64

In [134]:
df1.isna() #same as isnull()

    Name  Address    Age  Marks
0  False    False  False  False
1  False    False  False  False
2  False    False  False  False
3  False    False  False  False
4  False    False  False  False
5  False    False  False  False

In [135]:
df1.index    # index starts from 0, ends at 6(not included) and goes up by 1 each time

RangeIndex(start=0, stop=6, step=1)

In [136]:
df1.index[0] #first index starts from

0

In [137]:
len(df.index) #number of rows

6

In [138]:
df.index.to_list()

[0, 1, 2, 3, 4, 5]

In [139]:
df1.duplicated() # finds duplicate rows in your DataFrame

0    False
1    False
2    False
3    False
4     True
5    False
dtype: bool

In [140]:
df1.duplicated().sum()

np.int64(1)

In [141]:
df1[df1.duplicated(keep = False)] 

# 'first' -> Marks the second and later occurrences as duplicate, first one is safe (default)
# 'last' -> Marks the first and earlier occurrences as duplicate, last one is safe
# False -> Marks ALL occurrences as duplicate

     Name    Address  Age  Marks
2  Thomas  Koteshwor   18     88
4  Thomas  Koteshwor   18     88

In [142]:
df1[df1.duplicated(subset =['Marks'],keep = False)] 

#subset -> tells pandas which columns to check for duplicates, instead of checking all columns
#can have multiple valeus as well subset = ['Name','Marks']

     Name    Address  Age  Marks
1    Bini   Dudhpati   19     91
2  Thomas  Koteshwor   18     88
3  Simran  Pepsicola   19     91
4  Thomas  Koteshwor   18     88

In [143]:
df1.drop_duplicates(inplace = True)
# df1 = df1.drop_duplicates()

In [144]:
df1

     Name     Address  Age  Marks
0  Ashuka  Naya Thimi   20     90
1    Bini    Dudhpati   19     91
2  Thomas   Koteshwor   18     88
3  Simran   Pepsicola   19     91
5  Dipesh   Baneshwor   22     97

In [145]:
df1.drop(columns = 'Marks', inplace = True, axis = 1)

# axis -> tells pandas which direction to work in, rows or columns
# axis = 0 -> works on rows
# axis = 1 -> works on columns

In [146]:
df1

     Name     Address  Age
0  Ashuka  Naya Thimi   20
1    Bini    Dudhpati   19
2  Thomas   Koteshwor   18
3  Simran   Pepsicola   19
5  Dipesh   Baneshwor   22

In [147]:
df1.drop(0, inplace = True, axis = 0) # deletes the first row

In [148]:
df1

     Name    Address  Age
1    Bini   Dudhpati   19
2  Thomas  Koteshwor   18
3  Simran  Pepsicola   19
5  Dipesh  Baneshwor   22