In [23]:
import pandas as pd
import numpy as np
import os
import math
from datetime import datetime
from dateutil.relativedelta import relativedelta

##### relativedelta is a tool from the dateutil library that helps you calculate differences between dates or add/subtract time more accurately than normal Python

In [24]:
df = pd.DataFrame(
    {
        'Name': ['Aaron', 'Bella', 'Charles', 'Diana', 'Ella', 
                 'Frank', 'Gabriel', 'Hannah', 'Ian', 'Julia', 
                 'Kevin', 'Leah', 'Marcus', 'Natan', 'Olivia', 
                 'Penelope', 'Quentin', 'Rachel', 'Samuel', 'Tessa'],
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Female',
                   'Male', 'Male', 'Female', 'Male', 'Female', 
                   'Male', 'Female', 'Male',  'Male', 'Female', 
                   'Female',  'Male',  'Female', 'Male', 'Female'],
        'DOB': ['1990-05-12', '1993-11-03', '1988-07-21', '1995-02-14', '1992-09-30',
                '1987-04-18', '1991-12-25', '1996-06-09', '1989-03-05', '1994-08-22',
                '1986-01-17', '1997-10-11', '1990-12-02', '1993-05-27', '1988-11-15', 
                '1992-07-04', '1985-09-19', '1996-03-28', '1991-12-08', '1995-01-30'],
        'Age': [35, 32, 37, 31, 33, 
                38, 34, 29, 37, 31,
                40, 28, 35, 32, 37,
                33, 40, 29, 34, 31],
        'DOD': ["Alive", "Alive", "Dead", "Alive", "Alive", 
                "Dead", "Alive", "Alive", "Alive", "Alive",
                "Dead", "Alive", "Alive", "Alive", "Alive", 
                "Alive","Dead", "Alive", "Alive", "Alive"],
        'Address': ['Kathmandu', 'Bhaktapur', 'Lalitpur', 'Sunsari', 'Pokhara',
                   'Chitwan', 'Dhangadi', 'Jhapa', 'Biratnagar', 'Lumbini',
                   'Janakpur', 'Nepalgunj', 'Daang', 'Palpa', 'Gorkha',
                   'Butwal', 'Illam', 'Lamjung', 'Kavre', 'Rautahat'],
        'Salary': [95000, 72000, 58000, 90000, 90000, 
                   55000, 68000, 70000, 85000, 62000,
                   60000, 85000, 98000, 76000, 95000,
                   88000, 47000, 73000, 82000, 69000],
        'Post': ["Software Engineer", "Marketing Manager", "Teacher", "Data Analyst", "Financial Advisor", 
                 "Nurse", "Architect", "HR Specialist", "Research Scientist", "Journalist", 
                 "Mechanic", "Lawyer", "Project Manager", "Graphic Designer", "Software Architect", 
                 "Product Manager", "Chef", "Social Worker", "Civil Engineer", "Teacher"],
        'Education': ["B.Sc. Computer Sci", "MBA Marketing", "M.Ed. Education", "B.Sc. Statistics", "MBA Finance",
                      "B.Sc. Nursing", "M.Architecture", "B.A. Psychology", "Ph.D. Chemistry", "B.A. Journalism",
                      "Diploma Engg.", "J.D. Law", "MBA Management", "BFA Design", "M.Sc. Computer Sci",
                      "MBA Strategy", "Culinary Diploma", "M.A. Sociology", "B.Sc. Civil Engg", "M.Ed. Education"],
        'CGPA': [3.4, 3.6, 3.2, 3.7, 3.5, 
                 3.1, 3.3, 3.6, 3.8, 3.4,
                 2.9, 3.7, 3.5, 3.2, 3.9, 
                 3.6, 3.0, 3.4, 3.5, 3.3]
    }
)

#### Basic data pre-processing and data inspection

In [25]:
df.head()

,Name,Gender,DOB,Age,DOD,Address,Salary,Post,Education,CGPA
0,Aaron,Male,1990-05-12,35,Alive,Kathmandu,95000,Software Engineer,B.Sc. Computer Sci,3.4
1,Bella,Female,1993-11-03,32,Alive,Bhaktapur,72000,Marketing Manager,MBA Marketing,3.6
2,Charles,Male,1988-07-21,37,Dead,Lalitpur,58000,Teacher,M.Ed. Education,3.2
3,Diana,Female,1995-02-14,31,Alive,Sunsari,90000,Data Analyst,B.Sc. Statistics,3.7
4,Ella,Female,1992-09-30,33,Alive,Pokhara,90000,Financial Advisor,MBA Finance,3.5

In [26]:
# making a directory

os.makedirs('Data_Sets',exist_ok = True)

In [27]:
# converting the dataframe to a csv fiel and then, saving it in the created directory

df.to_csv('Data_Sets/Employee_Details.csv',index = False)

In [28]:
df.tail()

,Name,Gender,DOB,Age,DOD,Address,Salary,Post,Education,CGPA
15,Penelope,Female,1992-07-04,33,Alive,Butwal,88000,Product Manager,MBA Strategy,3.6
16,Quentin,Male,1985-09-19,40,Dead,Illam,47000,Chef,Culinary Diploma,3.0
17,Rachel,Female,1996-03-28,29,Alive,Lamjung,73000,Social Worker,M.A. Sociology,3.4
18,Samuel,Male,1991-12-08,34,Alive,Kavre,82000,Civil Engineer,B.Sc. Civil Engg,3.5
19,Tessa,Female,1995-01-30,31,Alive,Rautahat,69000,Teacher,M.Ed. Education,3.3

In [29]:
df.sample(5) # gives random samples from the dataframe

,Name,Gender,DOB,Age,DOD,Address,Salary,Post,Education,CGPA
18,Samuel,Male,1991-12-08,34,Alive,Kavre,82000,Civil Engineer,B.Sc. Civil Engg,3.5
7,Hannah,Female,1996-06-09,29,Alive,Jhapa,70000,HR Specialist,B.A. Psychology,3.6
9,Julia,Female,1994-08-22,31,Alive,Lumbini,62000,Journalist,B.A. Journalism,3.4
15,Penelope,Female,1992-07-04,33,Alive,Butwal,88000,Product Manager,MBA Strategy,3.6
19,Tessa,Female,1995-01-30,31,Alive,Rautahat,69000,Teacher,M.Ed. Education,3.3

In [30]:
df.dtypes # gives the data type of the entire dataframe

Name          object
Gender        object
DOB           object
Age            int64
DOD           object
Address       object
Salary         int64
Post          object
Education     object
CGPA         float64
dtype: object

In [31]:
df['Salary'].dtypes # to know the datatype of a single column

dtype('int64')

In [32]:
# changing the data type

df['Salary'] = df['Salary'].astype(float)

In [33]:
df.dtypes

Name          object
Gender        object
DOB           object
Age            int64
DOD           object
Address       object
Salary       float64
Post          object
Education     object
CGPA         float64
dtype: object

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       20 non-null     object
 1   Gender     20 non-null     object
 2   DOB        20 non-null     object
 3   Age        20 non-null     int64
 4   DOD        20 non-null     object
 5   Address    20 non-null     object
 6   Salary     20 non-null     float64
 7   Post       20 non-null     object
 8   Education  20 non-null     object
 9   CGPA       20 non-null     float64
dtypes: float64(2), int64(1), object(7)
memory usage: 1.7+ KB

In [35]:
df.isnull()

,Name,Gender,DOB,Age,DOD,Address,Salary,Post,Education,CGPA
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False

In [36]:
df.isnull().sum()

Name         0
Gender       0
DOB          0
Age          0
DOD          0
Address      0
Salary       0
Post         0
Education    0
CGPA         0
dtype: int64

In [37]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
dtype: bool

In [38]:
df.duplicated().sum()

np.int64(0)

In [39]:
df.describe(include = 'all')

,Name,Gender,DOB,Age,DOD,Address,Salary,Post,Education,CGPA
count,20,20,20,20.000000,20,20,20.000000,20,20,20.000000
unique,20,2,20,NaN,2,20,NaN,19,19,NaN
top,Aaron,Male,1990-05-12,NaN,Alive,Kathmandu,NaN,Teacher,M.Ed. Education,NaN
freq,1,10,1,NaN,16,1,NaN,2,2,NaN
mean,NaN,NaN,NaN,33.800000,NaN,NaN,75900.000000,NaN,NaN,3.430000
std,NaN,NaN,NaN,3.548165,NaN,NaN,14817.841309,NaN,NaN,0.263778
min,NaN,NaN,NaN,28.000000,NaN,NaN,47000.000000,NaN,NaN,2.900000
25%,NaN,NaN,NaN,31.000000,NaN,NaN,66500.000000,NaN,NaN,3.275000
50%,NaN,NaN,NaN,33.500000,NaN,NaN,74500.000000,NaN,NaN,3.450000
75%,NaN,NaN,NaN,37.000000,NaN,NaN,88500.000000,NaN,NaN,3.600000
max,NaN,NaN,NaN,40.000000,NaN,NaN,98000.000000,NaN,NaN,3.900000

##### Qn: If salary of an employee greater than 50000, display their name, gender, post, salary

In [40]:
df[['Name','Gender','Post','Salary']][df['Salary'] > 50000] # viewing data by filtering

        Name  Gender                Post   Salary
0      Aaron    Male   Software Engineer  95000.0
1      Bella  Female   Marketing Manager  72000.0
2    Charles    Male             Teacher  58000.0
3      Diana  Female        Data Analyst  90000.0
4       Ella  Female   Financial Advisor  90000.0
5      Frank    Male               Nurse  55000.0
6    Gabriel    Male           Architect  68000.0
7     Hannah  Female       HR Specialist  70000.0
8        Ian    Male  Research Scientist  85000.0
9      Julia  Female          Journalist  62000.0
10     Kevin    Male            Mechanic  60000.0
11      Leah  Female              Lawyer  85000.0
12    Marcus    Male     Project Manager  98000.0
13     Natan    Male    Graphic Designer  76000.0
14    Olivia  Female  Software Architect  95000.0
15  Penelope  Female     Product Manager  88000.0
17    Rachel  Female       Social Worker  73000.0
18    Samuel    Male      Civil Engineer  82000.0
19     Tessa  Female             Teacher  69000.0

In [41]:
df['DOB'] = pd.to_datetime(df['DOB'], format = '%Y-%m-%d')

In [42]:
df['DOB']

0    1990-05-12
1    1993-11-03
2    1988-07-21
3    1995-02-14
4    1992-09-30
5    1987-04-18
6    1991-12-25
7    1996-06-09
8    1989-03-05
9    1994-08-22
10   1986-01-17
11   1997-10-11
12   1990-12-02
13   1993-05-27
14   1988-11-15
15   1992-07-04
16   1985-09-19
17   1996-03-28
18   1991-12-08
19   1995-01-30
Name: DOB, dtype: datetime64[ns]

In [43]:
# Today's Date and Time
today = pd.to_datetime('today') 
today

Timestamp('2026-03-16 14:24:41.634569')

In [44]:
# dt is a date accessor in pandas —> it lets you extract specific parts from a date column

df['DOB'].dt.year

0     1990
1     1993
2     1988
3     1995
4     1992
5     1987
6     1991
7     1996
8     1989
9     1994
10    1986
11    1997
12    1990
13    1993
14    1988
15    1992
16    1985
17    1996
18    1991
19    1995
Name: DOB, dtype: int32

In [45]:
# feature engineering -> creating new column based on existing ones
# creating new column 'Year','Month' and 'Day' based on 'DOB'

df['Year'] = df['DOB'].dt.year
df['Month'] = df['DOB'].dt.month
df['Day'] = df['DOB'].dt.day

In [46]:
df.head()

,Name,Gender,DOB,Age,DOD,Address,Salary,Post,Education,CGPA,Year,Month,Day
0,Aaron,Male,1990-05-12,35,Alive,Kathmandu,95000.0,Software Engineer,B.Sc. Computer Sci,3.4,1990,5,12
1,Bella,Female,1993-11-03,32,Alive,Bhaktapur,72000.0,Marketing Manager,MBA Marketing,3.6,1993,11,3
2,Charles,Male,1988-07-21,37,Dead,Lalitpur,58000.0,Teacher,M.Ed. Education,3.2,1988,7,21
3,Diana,Female,1995-02-14,31,Alive,Sunsari,90000.0,Data Analyst,B.Sc. Statistics,3.7,1995,2,14
4,Ella,Female,1992-09-30,33,Alive,Pokhara,90000.0,Financial Advisor,MBA Finance,3.5,1992,9,30

In [47]:
df.dtypes

Name                 object
Gender               object
DOB          datetime64[ns]
Age                   int64
DOD                  object
Address              object
Salary              float64
Post                 object
Education            object
CGPA                float64
Year                  int32
Month                 int32
Day                   int32
dtype: object

In [48]:
# deleting columns

df.drop(['Age','DOD'], inplace = True, axis = 1)

In [49]:
df.head()

,Name,Gender,DOB,Address,Salary,Post,Education,CGPA,Year,Month,Day
0,Aaron,Male,1990-05-12,Kathmandu,95000.0,Software Engineer,B.Sc. Computer Sci,3.4,1990,5,12
1,Bella,Female,1993-11-03,Bhaktapur,72000.0,Marketing Manager,MBA Marketing,3.6,1993,11,3
2,Charles,Male,1988-07-21,Lalitpur,58000.0,Teacher,M.Ed. Education,3.2,1988,7,21
3,Diana,Female,1995-02-14,Sunsari,90000.0,Data Analyst,B.Sc. Statistics,3.7,1995,2,14
4,Ella,Female,1992-09-30,Pokhara,90000.0,Financial Advisor,MBA Finance,3.5,1992,9,30

In [50]:
# Creating new column 'Age' deriving from DOB and current time -> Feature Engineering
# current year - dob (cannot give accurate since age depends on month and day)

today = datetime.today()
today

datetime.datetime(2026, 3, 16, 14, 24, 41, 750077)

In [51]:
today = datetime.today()

def calculate_age(dob):
    diff = relativedelta(today,dob)
    return f'{diff.years} Year {diff.months} Month {diff.days} days'

df['Age'] = df['DOB'].apply(calculate_age)

In [52]:
#  apply -> runs a function on every row
# It sends one value at a time into the function, gets the result, and moves to the next
# faster and cleaner than loops

In [53]:
df.head()

,Name,Gender,DOB,Address,Salary,Post,Education,CGPA,Year,Month,Day,Age
0,Aaron,Male,1990-05-12,Kathmandu,95000.0,Software Engineer,B.Sc. Computer Sci,3.4,1990,5,12,35 Year 10 Month 4 days
1,Bella,Female,1993-11-03,Bhaktapur,72000.0,Marketing Manager,MBA Marketing,3.6,1993,11,3,32 Year 4 Month 13 days
2,Charles,Male,1988-07-21,Lalitpur,58000.0,Teacher,M.Ed. Education,3.2,1988,7,21,37 Year 7 Month 23 days
3,Diana,Female,1995-02-14,Sunsari,90000.0,Data Analyst,B.Sc. Statistics,3.7,1995,2,14,31 Year 1 Month 2 days
4,Ella,Female,1992-09-30,Pokhara,90000.0,Financial Advisor,MBA Finance,3.5,1992,9,30,33 Year 5 Month 16 days

In [54]:
df.drop(columns = 'Age', inplace = True, axis = 1)

In [55]:
df.head()

,Name,Gender,DOB,Address,Salary,Post,Education,CGPA,Year,Month,Day
0,Aaron,Male,1990-05-12,Kathmandu,95000.0,Software Engineer,B.Sc. Computer Sci,3.4,1990,5,12
1,Bella,Female,1993-11-03,Bhaktapur,72000.0,Marketing Manager,MBA Marketing,3.6,1993,11,3
2,Charles,Male,1988-07-21,Lalitpur,58000.0,Teacher,M.Ed. Education,3.2,1988,7,21
3,Diana,Female,1995-02-14,Sunsari,90000.0,Data Analyst,B.Sc. Statistics,3.7,1995,2,14
4,Ella,Female,1992-09-30,Pokhara,90000.0,Financial Advisor,MBA Finance,3.5,1992,9,30

In [56]:
df['Age'] = df['DOB'].apply(lambda dob: relativedelta(today,dob).years)

In [57]:
df.head()

,Name,Gender,DOB,Address,Salary,Post,Education,CGPA,Year,Month,Day,Age
0,Aaron,Male,1990-05-12,Kathmandu,95000.0,Software Engineer,B.Sc. Computer Sci,3.4,1990,5,12,35
1,Bella,Female,1993-11-03,Bhaktapur,72000.0,Marketing Manager,MBA Marketing,3.6,1993,11,3,32
2,Charles,Male,1988-07-21,Lalitpur,58000.0,Teacher,M.Ed. Education,3.2,1988,7,21,37
3,Diana,Female,1995-02-14,Sunsari,90000.0,Data Analyst,B.Sc. Statistics,3.7,1995,2,14,31
4,Ella,Female,1992-09-30,Pokhara,90000.0,Financial Advisor,MBA Finance,3.5,1992,9,30,33

In [58]:
# value_counts -> counts how many times each value appears

df['Gender'].value_counts()

Gender
Male      10
Female    10
Name: count, dtype: int64

In [59]:
df['Post'].value_counts()

Post
Teacher               2
Software Engineer     1
Mechanic              1
Social Worker         1
Chef                  1
Product Manager       1
Software Architect    1
Graphic Designer      1
Project Manager       1
Lawyer                1
Journalist            1
Marketing Manager     1
Research Scientist    1
HR Specialist         1
Architect             1
Nurse                 1
Financial Advisor     1
Data Analyst          1
Civil Engineer        1
Name: count, dtype: int64

##### Group by function
- lets you group rows based on columns
- Printing groupby alone shows a memory address
- just groups and selects the column

In [60]:
df.groupby('Gender')['Salary']

In [61]:
df.groupby('Gender')['Salary'].mean()

Gender
Female    79400.0
Male      72400.0
Name: Salary, dtype: float64

In [62]:
df.groupby('Gender')['Salary'].min()

Gender
Female    62000.0
Male      47000.0
Name: Salary, dtype: float64

In [63]:
# to see all groups use get_group

df.groupby('Gender').get_group('Male')

,Name,Gender,DOB,Address,Salary,Post,Education,CGPA,Year,Month,Day,Age
0,Aaron,Male,1990-05-12,Kathmandu,95000.0,Software Engineer,B.Sc. Computer Sci,3.4,1990,5,12,35
2,Charles,Male,1988-07-21,Lalitpur,58000.0,Teacher,M.Ed. Education,3.2,1988,7,21,37
5,Frank,Male,1987-04-18,Chitwan,55000.0,Nurse,B.Sc. Nursing,3.1,1987,4,18,38
6,Gabriel,Male,1991-12-25,Dhangadi,68000.0,Architect,M.Architecture,3.3,1991,12,25,34
8,Ian,Male,1989-03-05,Biratnagar,85000.0,Research Scientist,Ph.D. Chemistry,3.8,1989,3,5,37
10,Kevin,Male,1986-01-17,Janakpur,60000.0,Mechanic,Diploma Engg.,2.9,1986,1,17,40
12,Marcus,Male,1990-12-02,Daang,98000.0,Project Manager,MBA Management,3.5,1990,12,2,35
13,Natan,Male,1993-05-27,Palpa,76000.0,Graphic Designer,BFA Design,3.2,1993,5,27,32
16,Quentin,Male,1985-09-19,Illam,47000.0,Chef,Culinary Diploma,3.0,1985,9,19,40
18,Samuel,Male,1991-12-08,Kavre,82000.0,Civil Engineer,B.Sc. Civil Engg,3.5,1991,12,8,34

In [64]:
# selecting a particular column of the group

df.groupby('Gender').get_group('Male')['Salary']

0     95000.0
2     58000.0
5     55000.0
6     68000.0
8     85000.0
10    60000.0
12    98000.0
13    76000.0
16    47000.0
18    82000.0
Name: Salary, dtype: float64

##### Qn: Increase salary by 15% for male with cgpa >= 3.5 into a new salary

In [65]:
# checking the employeees who are male with cgpa >= 3.5

df[['Name','CGPA','Salary']][(df['Gender'] == 'Male') & (df['CGPA'] >= 3.5)]

      Name  CGPA   Salary
8      Ian   3.8  85000.0
12  Marcus   3.5  98000.0
18  Samuel   3.5  82000.0

In [66]:
# Method - 1

def increase_sal(x):
    if (x['Gender'] == 'Male') & (x['CGPA'] >= 3.5):
        return x['Salary'] * 1.15
    else:
         return x['Salary']

df['Updated_Salary'] = df.apply(increase_sal,axis = 1)

In [67]:
df

,Name,Gender,DOB,Address,Salary,Post,Education,CGPA,Year,Month,Day,Age,Updated_Salary
0,Aaron,Male,1990-05-12,Kathmandu,95000.0,Software Engineer,B.Sc. Computer Sci,3.4,1990,5,12,35,95000.0
1,Bella,Female,1993-11-03,Bhaktapur,72000.0,Marketing Manager,MBA Marketing,3.6,1993,11,3,32,72000.0
2,Charles,Male,1988-07-21,Lalitpur,58000.0,Teacher,M.Ed. Education,3.2,1988,7,21,37,58000.0
3,Diana,Female,1995-02-14,Sunsari,90000.0,Data Analyst,B.Sc. Statistics,3.7,1995,2,14,31,90000.0
4,Ella,Female,1992-09-30,Pokhara,90000.0,Financial Advisor,MBA Finance,3.5,1992,9,30,33,90000.0
5,Frank,Male,1987-04-18,Chitwan,55000.0,Nurse,B.Sc. Nursing,3.1,1987,4,18,38,55000.0
6,Gabriel,Male,1991-12-25,Dhangadi,68000.0,Architect,M.Architecture,3.3,1991,12,25,34,68000.0
7,Hannah,Female,1996-06-09,Jhapa,70000.0,HR Specialist,B.A. Psychology,3.6,1996,6,9,29,70000.0
8,Ian,Male,1989-03-05,Biratnagar,85000.0,Research Scientist,Ph.D. Chemistry,3.8,1989,3,5,37,97750.0
9,Julia,Female,1994-08-22,Lumbini,62000.0,Journalist,B.A. Journalism,3.4,1994,8,22,31,62000.0
10,Kevin,Male,1986-01-17,Janakpur,60000.0,Mechanic,Diploma Engg.,2.9,1986,1,17,40,60000.0
11,Leah,Female,1997-10-11,Nepalgunj,85000.0,Lawyer,J.D. Law,3.7,1997,10,11,28,85000.0
12,Marcus,Male,1990-12-02,Daang,98000.0,Project Manager,MBA Management,3.5,1990,12,2,35,112700.0
13,Natan,Male,1993-05-27,Palpa,76000.0,Graphic Designer,BFA Design,3.2,1993,5,27,32,76000.0
14,Olivia,Female,1988-11-15,Gorkha,95000.0,Software Architect,M.Sc. Computer Sci,3.9,1988,11,15,37,95000.0
15,Penelope,Female,1992-07-04,Butwal,88000.0,Product Manager,MBA Strategy,3.6,1992,7,4,33,88000.0
16,Quentin,Male,1985-09-19,Illam,47000.0,Chef,Culinary Diploma,3.0,1985,9,19,40,47000.0
17,Rachel,Female,1996-03-28,Lamjung,73000.0,Social Worker,M.A. Sociology,3.4,1996,3,28,29,73000.0
18,Samuel,Male,1991-12-08,Kavre,82000.0,Civil Engineer,B.Sc. Civil Engg,3.5,1991,12,8,34,94300.0
19,Tessa,Female,1995-01-30,Rautahat,69000.0,Teacher,M.Ed. Education,3.3,1995,1,30,31,69000.0

In [68]:
df.drop(columns = 'Updated_Salary', inplace = True)

In [69]:
df.head()

,Name,Gender,DOB,Address,Salary,Post,Education,CGPA,Year,Month,Day,Age
0,Aaron,Male,1990-05-12,Kathmandu,95000.0,Software Engineer,B.Sc. Computer Sci,3.4,1990,5,12,35
1,Bella,Female,1993-11-03,Bhaktapur,72000.0,Marketing Manager,MBA Marketing,3.6,1993,11,3,32
2,Charles,Male,1988-07-21,Lalitpur,58000.0,Teacher,M.Ed. Education,3.2,1988,7,21,37
3,Diana,Female,1995-02-14,Sunsari,90000.0,Data Analyst,B.Sc. Statistics,3.7,1995,2,14,31
4,Ella,Female,1992-09-30,Pokhara,90000.0,Financial Advisor,MBA Finance,3.5,1992,9,30,33

In [70]:
# Method - 2

# .loc includes the last label -> inclusive
# .iloc excludes the last position -> exclusive

i = (df['Gender'] == 'Male') & (df['CGPA'] >= 3.5)

df.loc[i,'Salary'] *= 1.15

df

,Name,Gender,DOB,Address,Salary,Post,Education,CGPA,Year,Month,Day,Age
0,Aaron,Male,1990-05-12,Kathmandu,95000.0,Software Engineer,B.Sc. Computer Sci,3.4,1990,5,12,35
1,Bella,Female,1993-11-03,Bhaktapur,72000.0,Marketing Manager,MBA Marketing,3.6,1993,11,3,32
2,Charles,Male,1988-07-21,Lalitpur,58000.0,Teacher,M.Ed. Education,3.2,1988,7,21,37
3,Diana,Female,1995-02-14,Sunsari,90000.0,Data Analyst,B.Sc. Statistics,3.7,1995,2,14,31
4,Ella,Female,1992-09-30,Pokhara,90000.0,Financial Advisor,MBA Finance,3.5,1992,9,30,33
5,Frank,Male,1987-04-18,Chitwan,55000.0,Nurse,B.Sc. Nursing,3.1,1987,4,18,38
6,Gabriel,Male,1991-12-25,Dhangadi,68000.0,Architect,M.Architecture,3.3,1991,12,25,34
7,Hannah,Female,1996-06-09,Jhapa,70000.0,HR Specialist,B.A. Psychology,3.6,1996,6,9,29
8,Ian,Male,1989-03-05,Biratnagar,97750.0,Research Scientist,Ph.D. Chemistry,3.8,1989,3,5,37
9,Julia,Female,1994-08-22,Lumbini,62000.0,Journalist,B.A. Journalism,3.4,1994,8,22,31
10,Kevin,Male,1986-01-17,Janakpur,60000.0,Mechanic,Diploma Engg.,2.9,1986,1,17,40
11,Leah,Female,1997-10-11,Nepalgunj,85000.0,Lawyer,J.D. Law,3.7,1997,10,11,28
12,Marcus,Male,1990-12-02,Daang,112700.0,Project Manager,MBA Management,3.5,1990,12,2,35
13,Natan,Male,1993-05-27,Palpa,76000.0,Graphic Designer,BFA Design,3.2,1993,5,27,32
14,Olivia,Female,1988-11-15,Gorkha,95000.0,Software Architect,M.Sc. Computer Sci,3.9,1988,11,15,37
15,Penelope,Female,1992-07-04,Butwal,88000.0,Product Manager,MBA Strategy,3.6,1992,7,4,33
16,Quentin,Male,1985-09-19,Illam,47000.0,Chef,Culinary Diploma,3.0,1985,9,19,40
17,Rachel,Female,1996-03-28,Lamjung,73000.0,Social Worker,M.A. Sociology,3.4,1996,3,28,29
18,Samuel,Male,1991-12-08,Kavre,94300.0,Civil Engineer,B.Sc. Civil Engg,3.5,1991,12,8,34
19,Tessa,Female,1995-01-30,Rautahat,69000.0,Teacher,M.Ed. Education,3.3,1995,1,30,31

#### .iloc
.iloc works like a matrix, access any cell using df.iloc[row, column] where both row and column are position numbers starting from 0. Just like matrix coordinates, df.iloc[1, 3] means row 1, column 3. It only accepts numbers, never names or labels

#### .loc 
.loc works like a matrix/grid, access any cell using df.loc[row_label, column_name] where row is the index label and column is the column name. Just like df.loc[1, 'Salary'] means row with label 1, column named Salary. The only difference from .iloc is that it uses labels/names instead of position numbers

In [71]:
# Method - 3 -> using lambda function

df['Salary'] = df.apply(lambda x: x['Salary'] * 1.15 if ((x['Gender'] == 'Male') & (x['CGPA'] >= 3.5)) else x['Salary'], axis = 1)

In [72]:
df

,Name,Gender,DOB,Address,Salary,Post,Education,CGPA,Year,Month,Day,Age
0,Aaron,Male,1990-05-12,Kathmandu,95000.0,Software Engineer,B.Sc. Computer Sci,3.4,1990,5,12,35
1,Bella,Female,1993-11-03,Bhaktapur,72000.0,Marketing Manager,MBA Marketing,3.6,1993,11,3,32
2,Charles,Male,1988-07-21,Lalitpur,58000.0,Teacher,M.Ed. Education,3.2,1988,7,21,37
3,Diana,Female,1995-02-14,Sunsari,90000.0,Data Analyst,B.Sc. Statistics,3.7,1995,2,14,31
4,Ella,Female,1992-09-30,Pokhara,90000.0,Financial Advisor,MBA Finance,3.5,1992,9,30,33
5,Frank,Male,1987-04-18,Chitwan,55000.0,Nurse,B.Sc. Nursing,3.1,1987,4,18,38
6,Gabriel,Male,1991-12-25,Dhangadi,68000.0,Architect,M.Architecture,3.3,1991,12,25,34
7,Hannah,Female,1996-06-09,Jhapa,70000.0,HR Specialist,B.A. Psychology,3.6,1996,6,9,29
8,Ian,Male,1989-03-05,Biratnagar,112412.5,Research Scientist,Ph.D. Chemistry,3.8,1989,3,5,37
9,Julia,Female,1994-08-22,Lumbini,62000.0,Journalist,B.A. Journalism,3.4,1994,8,22,31
10,Kevin,Male,1986-01-17,Janakpur,60000.0,Mechanic,Diploma Engg.,2.9,1986,1,17,40
11,Leah,Female,1997-10-11,Nepalgunj,85000.0,Lawyer,J.D. Law,3.7,1997,10,11,28
12,Marcus,Male,1990-12-02,Daang,129605.0,Project Manager,MBA Management,3.5,1990,12,2,35
13,Natan,Male,1993-05-27,Palpa,76000.0,Graphic Designer,BFA Design,3.2,1993,5,27,32
14,Olivia,Female,1988-11-15,Gorkha,95000.0,Software Architect,M.Sc. Computer Sci,3.9,1988,11,15,37
15,Penelope,Female,1992-07-04,Butwal,88000.0,Product Manager,MBA Strategy,3.6,1992,7,4,33
16,Quentin,Male,1985-09-19,Illam,47000.0,Chef,Culinary Diploma,3.0,1985,9,19,40
17,Rachel,Female,1996-03-28,Lamjung,73000.0,Social Worker,M.A. Sociology,3.4,1996,3,28,29
18,Samuel,Male,1991-12-08,Kavre,108445.0,Civil Engineer,B.Sc. Civil Engg,3.5,1991,12,8,34
19,Tessa,Female,1995-01-30,Rautahat,69000.0,Teacher,M.Ed. Education,3.3,1995,1,30,31

In [73]:
# Method - 4 -> using assign

df = df.assign(Salary = lambda x : np.where
         ( (x['Gender'] == 'Male') & (x['CGPA'] >= 3.5),  # condition
            x['Salary'] * 1.15, # if True
            x['Salary']  # if False    
         ))

In [74]:
# np.where works like if/else
# np.where(condition, value_if_true, value_if_false)

In [75]:
df

,Name,Gender,DOB,Address,Salary,Post,Education,CGPA,Year,Month,Day,Age
0,Aaron,Male,1990-05-12,Kathmandu,95000.000,Software Engineer,B.Sc. Computer Sci,3.4,1990,5,12,35
1,Bella,Female,1993-11-03,Bhaktapur,72000.000,Marketing Manager,MBA Marketing,3.6,1993,11,3,32
2,Charles,Male,1988-07-21,Lalitpur,58000.000,Teacher,M.Ed. Education,3.2,1988,7,21,37
3,Diana,Female,1995-02-14,Sunsari,90000.000,Data Analyst,B.Sc. Statistics,3.7,1995,2,14,31
4,Ella,Female,1992-09-30,Pokhara,90000.000,Financial Advisor,MBA Finance,3.5,1992,9,30,33
5,Frank,Male,1987-04-18,Chitwan,55000.000,Nurse,B.Sc. Nursing,3.1,1987,4,18,38
6,Gabriel,Male,1991-12-25,Dhangadi,68000.000,Architect,M.Architecture,3.3,1991,12,25,34
7,Hannah,Female,1996-06-09,Jhapa,70000.000,HR Specialist,B.A. Psychology,3.6,1996,6,9,29
8,Ian,Male,1989-03-05,Biratnagar,129274.375,Research Scientist,Ph.D. Chemistry,3.8,1989,3,5,37
9,Julia,Female,1994-08-22,Lumbini,62000.000,Journalist,B.A. Journalism,3.4,1994,8,22,31
10,Kevin,Male,1986-01-17,Janakpur,60000.000,Mechanic,Diploma Engg.,2.9,1986,1,17,40
11,Leah,Female,1997-10-11,Nepalgunj,85000.000,Lawyer,J.D. Law,3.7,1997,10,11,28
12,Marcus,Male,1990-12-02,Daang,149045.750,Project Manager,MBA Management,3.5,1990,12,2,35
13,Natan,Male,1993-05-27,Palpa,76000.000,Graphic Designer,BFA Design,3.2,1993,5,27,32
14,Olivia,Female,1988-11-15,Gorkha,95000.000,Software Architect,M.Sc. Computer Sci,3.9,1988,11,15,37
15,Penelope,Female,1992-07-04,Butwal,88000.000,Product Manager,MBA Strategy,3.6,1992,7,4,33
16,Quentin,Male,1985-09-19,Illam,47000.000,Chef,Culinary Diploma,3.0,1985,9,19,40
17,Rachel,Female,1996-03-28,Lamjung,73000.000,Social Worker,M.A. Sociology,3.4,1996,3,28,29
18,Samuel,Male,1991-12-08,Kavre,124711.750,Civil Engineer,B.Sc. Civil Engg,3.5,1991,12,8,34
19,Tessa,Female,1995-01-30,Rautahat,69000.000,Teacher,M.Ed. Education,3.3,1995,1,30,31

apply() -> works on both a Series and DataFrame. When used on a Series like df['Salary'].apply(func) it passes one value at a time into the function. When used on a DataFrame like df.apply(func, axis=1) it passes one entire row at a time. Best used for complex logic that needs multiple columns. axis=0 sends each column into the function, axis=1 sends each row into the function.

assign() -> works only on a DataFrame. The entire DataFrame is passed as x into the lambda like df.assign(Salary = lambda x: x['Salary'] * 1.15). It is faster than apply because it works on the entire DataFrame at once instead of row by row. Best used for adding or updating columns. It always creates a new column and if you want to update an existig column just use the same column name. Also, it does NOT save to original DataFrame.

map() -> works only on a Series. It transforms each value one by one like df['Salary'].map(lambda x: x * 1.15). Its most powerful feature is dictionary mapping where you can replace values like df['Gender'].map({'Male': 1, 'Female': 0}). Best used for replacing or converting values. It does NOT save changes to the original DataFrame automatically

In [76]:
# map

df['Gender'] = df['Gender'].map({
    'Female':1,
    'Male':0
})

df.head()

,Name,Gender,DOB,Address,Salary,Post,Education,CGPA,Year,Month,Day,Age
0,Aaron,0,1990-05-12,Kathmandu,95000.0,Software Engineer,B.Sc. Computer Sci,3.4,1990,5,12,35
1,Bella,1,1993-11-03,Bhaktapur,72000.0,Marketing Manager,MBA Marketing,3.6,1993,11,3,32
2,Charles,0,1988-07-21,Lalitpur,58000.0,Teacher,M.Ed. Education,3.2,1988,7,21,37
3,Diana,1,1995-02-14,Sunsari,90000.0,Data Analyst,B.Sc. Statistics,3.7,1995,2,14,31
4,Ella,1,1992-09-30,Pokhara,90000.0,Financial Advisor,MBA Finance,3.5,1992,9,30,33

So, map() -> must assign  
assign() -> must assign  
apply() -> must assign  
.loc[] -> saves automatically