#### Create a DataFrame with columns Name, Age, Gender, DOB, DOD, Address, Salary, Post, Education, CGPA of employees. Then, solve the given questions.

In [50]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Ram Sharma", "Sita Thapa", "Hari Prasad", "Gita Karki",
             "Bishnu Rai", "Maya Gurung", "Sunita Shrestha", "Rohan Magar",
             "Priya Tamang", "Anil Basnet", "Binod Adhikari", "Kamala Poudel",
             "Suresh Bhatt", "Puja Silwal", "Rajesh Koirala", "Anita Pandey",
             "Dipak Chaudhary", "Laxmi Bajracharya", "Nabin Dahal", "Sabita Yadav",
             "Ram Sharma", "Sita Thapa", "Hari Prasad"],          # ← 3 duplicates added

    "Age": [25, 30, 45, 28, 22, 38, 27, 35, 31, 24,
            42, 33, 29, 30, 50, 27, 40, 31, 24, 26,
            25, 30, 45],

    "Gender": ["Male", "Female", "Male", "Female", "Male",
               "Female", "Female", "Male", "Female", "Male",
               "Male", "Female", "Male", "Female", "Male",
               "Female", "Male", "Female", "Male", "Female",
               "Male", "Female", "Male"],

    "DOB": ["1999-01-15", "1994-03-22", "1979-07-10", "1996-11-05",
            "2002-06-18", "1986-09-30", "1997-04-25", "1989-12-14",
            "1993-08-07", "2000-02-19", "1982-05-23", "1991-10-11",
            "1995-03-17", "1994-07-29", "1974-01-08", "1997-06-03",
            "1984-11-21", "1993-04-16", "2000-09-27", "1998-12-02",
            "1999-01-15", "1994-03-22", "1979-07-10"],

    "DOD": ["Alive", "Alive", "2023-05-10", "Alive", "Alive",
            "Alive", "Alive", "2021-08-15", "Alive", "Alive",
            "Alive", "Alive", "Alive", "Alive", "2022-11-30",
            "Alive", "Alive", "Alive", "Alive", "Alive",
            "Alive", "Alive", "2023-05-10"],

    "Address": ["Kathmandu-01", "Pokhara-05", "Chitwan-03", "Butwal-07",
                "Biratnagar-02", "Kathmandu-10", "Pokhara-08", "Lalitpur-04",
                "Chitwan-06", "Butwal-09", "Biratnagar-11", "Kathmandu-15",
                "Pokhara-12", "Lalitpur-02", "Chitwan-14", "Butwal-03",
                "Biratnagar-07", "Kathmandu-06", "Pokhara-11", "Lalitpur-09",
                "Kathmandu-01", "Pokhara-05", "Chitwan-03"],

    "Salary": [25000, 45000, 80000, 32000, 20000,
               60000, 30000, 55000, 42000, 22000,
               70000, 48000, 35000, 50000, 95000,
               28000, 65000, 52000, 21000, 27000,
               25000, 45000, 80000],

    "Post": ["Junior Developer", "Accountant", "Senior Manager", "HR Executive",
             "Intern", "Project Manager", "Data Analyst", "Team Lead",
             "Marketing Executive", "Junior Developer", "Senior Developer",
             "Finance Manager", "Business Analyst", "HR Manager", "Director",
             "Data Analyst", "Senior Developer", "Accountant", "Intern",
             "Junior Developer", "Junior Developer", "Accountant", "Senior Manager"],

    "Education": ["Bachelors", "Bachelors", "Masters", "Bachelors", "Running",
                  "Masters", "Bachelors", "Masters", "Bachelors", "Running",
                  "Masters", "Masters", "Bachelors", "Masters", "PhD",
                  "Bachelors", "Masters", "Bachelors", "Running", "Bachelors",
                  "Bachelors", "Bachelors", "Masters"],

    "CGPA": [3.5, 3.8, 3.9, 3.6, 3.2,
             3.7, 3.4, 3.8, 3.5, 3.1,
             3.9, 3.6, 3.3, 3.7, 4.0,
             3.4, 3.8, 3.6, 3.0, 3.5,
             3.5, 3.8, 3.9]
})

df

,Name,Age,Gender,DOB,DOD,Address,Salary,Post,Education,CGPA
0,Ram Sharma,25,Male,1999-01-15,Alive,Kathmandu-01,25000,Junior Developer,Bachelors,3.5
1,Sita Thapa,30,Female,1994-03-22,Alive,Pokhara-05,45000,Accountant,Bachelors,3.8
2,Hari Prasad,45,Male,1979-07-10,2023-05-10,Chitwan-03,80000,Senior Manager,Masters,3.9
3,Gita Karki,28,Female,1996-11-05,Alive,Butwal-07,32000,HR Executive,Bachelors,3.6
4,Bishnu Rai,22,Male,2002-06-18,Alive,Biratnagar-02,20000,Intern,Running,3.2
5,Maya Gurung,38,Female,1986-09-30,Alive,Kathmandu-10,60000,Project Manager,Masters,3.7
6,Sunita Shrestha,27,Female,1997-04-25,Alive,Pokhara-08,30000,Data Analyst,Bachelors,3.4
7,Rohan Magar,35,Male,1989-12-14,2021-08-15,Lalitpur-04,55000,Team Lead,Masters,3.8
8,Priya Tamang,31,Female,1993-08-07,Alive,Chitwan-06,42000,Marketing Executive,Bachelors,3.5
9,Anil Basnet,24,Male,2000-02-19,Alive,Butwal-09,22000,Junior Developer,Running,3.1
10,Binod Adhikari,42,Male,1982-05-23,Alive,Biratnagar-11,70000,Senior Developer,Masters,3.9
11,Kamala Poudel,33,Female,1991-10-11,Alive,Kathmandu-15,48000,Finance Manager,Masters,3.6
12,Suresh Bhatt,29,Male,1995-03-17,Alive,Pokhara-12,35000,Business Analyst,Bachelors,3.3
13,Puja Silwal,30,Female,1994-07-29,Alive,Lalitpur-02,50000,HR Manager,Masters,3.7
14,Rajesh Koirala,50,Male,1974-01-08,2022-11-30,Chitwan-14,95000,Director,PhD,4.0
15,Anita Pandey,27,Female,1997-06-03,Alive,Butwal-03,28000,Data Analyst,Bachelors,3.4
16,Dipak Chaudhary,40,Male,1984-11-21,Alive,Biratnagar-07,65000,Senior Developer,Masters,3.8
17,Laxmi Bajracharya,31,Female,1993-04-16,Alive,Kathmandu-06,52000,Accountant,Bachelors,3.6
18,Nabin Dahal,24,Male,2000-09-27,Alive,Pokhara-11,21000,Intern,Running,3.0
19,Sabita Yadav,26,Female,1998-12-02,Alive,Lalitpur-09,27000,Junior Developer,Bachelors,3.5
20,Ram Sharma,25,Male,1999-01-15,Alive,Kathmandu-01,25000,Junior Developer,Bachelors,3.5
21,Sita Thapa,30,Female,1994-03-22,Alive,Pokhara-05,45000,Accountant,Bachelors,3.8
22,Hari Prasad,45,Male,1979-07-10,2023-05-10,Chitwan-03,80000,Senior Manager,Masters,3.9

### Questions:

#### 1. Show the first 5 rows of the DataFrame

In [51]:
df.head()

,Name,Age,Gender,DOB,DOD,Address,Salary,Post,Education,CGPA
0,Ram Sharma,25,Male,1999-01-15,Alive,Kathmandu-01,25000,Junior Developer,Bachelors,3.5
1,Sita Thapa,30,Female,1994-03-22,Alive,Pokhara-05,45000,Accountant,Bachelors,3.8
2,Hari Prasad,45,Male,1979-07-10,2023-05-10,Chitwan-03,80000,Senior Manager,Masters,3.9
3,Gita Karki,28,Female,1996-11-05,Alive,Butwal-07,32000,HR Executive,Bachelors,3.6
4,Bishnu Rai,22,Male,2002-06-18,Alive,Biratnagar-02,20000,Intern,Running,3.2

#### 2. Show the last 3 rows of the DataFrame

In [52]:
df.tail(3)

,Name,Age,Gender,DOB,DOD,Address,Salary,Post,Education,CGPA
20,Ram Sharma,25,Male,1999-01-15,Alive,Kathmandu-01,25000,Junior Developer,Bachelors,3.5
21,Sita Thapa,30,Female,1994-03-22,Alive,Pokhara-05,45000,Accountant,Bachelors,3.8
22,Hari Prasad,45,Male,1979-07-10,2023-05-10,Chitwan-03,80000,Senior Manager,Masters,3.9

#### 3. Show only the Name and Salary columns

In [53]:
df[['Name','Salary']]

                 Name  Salary
0          Ram Sharma   25000
1          Sita Thapa   45000
2         Hari Prasad   80000
3          Gita Karki   32000
4          Bishnu Rai   20000
5         Maya Gurung   60000
6     Sunita Shrestha   30000
7         Rohan Magar   55000
8        Priya Tamang   42000
9         Anil Basnet   22000
10     Binod Adhikari   70000
11      Kamala Poudel   48000
12       Suresh Bhatt   35000
13        Puja Silwal   50000
14     Rajesh Koirala   95000
15       Anita Pandey   28000
16    Dipak Chaudhary   65000
17  Laxmi Bajracharya   52000
18        Nabin Dahal   21000
19       Sabita Yadav   27000
20         Ram Sharma   25000
21         Sita Thapa   45000
22        Hari Prasad   80000

#### 4. Show the shape of the DataFrame

In [54]:
df.shape

(23, 10)

#### 5. Show the data types of all columns

In [55]:
df.dtypes

Name          object
Age            int64
Gender        object
DOB           object
DOD           object
Address       object
Salary         int64
Post          object
Education     object
CGPA         float64
dtype: object

#### 6. Show all employees whose Age is greater than 30

In [56]:
df[df['Age'] > 30]

,Name,Age,Gender,DOB,DOD,Address,Salary,Post,Education,CGPA
2,Hari Prasad,45,Male,1979-07-10,2023-05-10,Chitwan-03,80000,Senior Manager,Masters,3.9
5,Maya Gurung,38,Female,1986-09-30,Alive,Kathmandu-10,60000,Project Manager,Masters,3.7
7,Rohan Magar,35,Male,1989-12-14,2021-08-15,Lalitpur-04,55000,Team Lead,Masters,3.8
8,Priya Tamang,31,Female,1993-08-07,Alive,Chitwan-06,42000,Marketing Executive,Bachelors,3.5
10,Binod Adhikari,42,Male,1982-05-23,Alive,Biratnagar-11,70000,Senior Developer,Masters,3.9
11,Kamala Poudel,33,Female,1991-10-11,Alive,Kathmandu-15,48000,Finance Manager,Masters,3.6
14,Rajesh Koirala,50,Male,1974-01-08,2022-11-30,Chitwan-14,95000,Director,PhD,4.0
16,Dipak Chaudhary,40,Male,1984-11-21,Alive,Biratnagar-07,65000,Senior Developer,Masters,3.8
17,Laxmi Bajracharya,31,Female,1993-04-16,Alive,Kathmandu-06,52000,Accountant,Bachelors,3.6
22,Hari Prasad,45,Male,1979-07-10,2023-05-10,Chitwan-03,80000,Senior Manager,Masters,3.9

#### 7. Show all Female employees

In [57]:
df[df['Gender'] == 'Female']

,Name,Age,Gender,DOB,DOD,Address,Salary,Post,Education,CGPA
1,Sita Thapa,30,Female,1994-03-22,Alive,Pokhara-05,45000,Accountant,Bachelors,3.8
3,Gita Karki,28,Female,1996-11-05,Alive,Butwal-07,32000,HR Executive,Bachelors,3.6
5,Maya Gurung,38,Female,1986-09-30,Alive,Kathmandu-10,60000,Project Manager,Masters,3.7
6,Sunita Shrestha,27,Female,1997-04-25,Alive,Pokhara-08,30000,Data Analyst,Bachelors,3.4
8,Priya Tamang,31,Female,1993-08-07,Alive,Chitwan-06,42000,Marketing Executive,Bachelors,3.5
11,Kamala Poudel,33,Female,1991-10-11,Alive,Kathmandu-15,48000,Finance Manager,Masters,3.6
13,Puja Silwal,30,Female,1994-07-29,Alive,Lalitpur-02,50000,HR Manager,Masters,3.7
15,Anita Pandey,27,Female,1997-06-03,Alive,Butwal-03,28000,Data Analyst,Bachelors,3.4
17,Laxmi Bajracharya,31,Female,1993-04-16,Alive,Kathmandu-06,52000,Accountant,Bachelors,3.6
19,Sabita Yadav,26,Female,1998-12-02,Alive,Lalitpur-09,27000,Junior Developer,Bachelors,3.5
21,Sita Thapa,30,Female,1994-03-22,Alive,Pokhara-05,45000,Accountant,Bachelors,3.8

#### 8. Show all employees who are Alive

In [58]:
df[df['DOD'] == 'Alive']

,Name,Age,Gender,DOB,DOD,Address,Salary,Post,Education,CGPA
0,Ram Sharma,25,Male,1999-01-15,Alive,Kathmandu-01,25000,Junior Developer,Bachelors,3.5
1,Sita Thapa,30,Female,1994-03-22,Alive,Pokhara-05,45000,Accountant,Bachelors,3.8
3,Gita Karki,28,Female,1996-11-05,Alive,Butwal-07,32000,HR Executive,Bachelors,3.6
4,Bishnu Rai,22,Male,2002-06-18,Alive,Biratnagar-02,20000,Intern,Running,3.2
5,Maya Gurung,38,Female,1986-09-30,Alive,Kathmandu-10,60000,Project Manager,Masters,3.7
6,Sunita Shrestha,27,Female,1997-04-25,Alive,Pokhara-08,30000,Data Analyst,Bachelors,3.4
8,Priya Tamang,31,Female,1993-08-07,Alive,Chitwan-06,42000,Marketing Executive,Bachelors,3.5
9,Anil Basnet,24,Male,2000-02-19,Alive,Butwal-09,22000,Junior Developer,Running,3.1
10,Binod Adhikari,42,Male,1982-05-23,Alive,Biratnagar-11,70000,Senior Developer,Masters,3.9
11,Kamala Poudel,33,Female,1991-10-11,Alive,Kathmandu-15,48000,Finance Manager,Masters,3.6
12,Suresh Bhatt,29,Male,1995-03-17,Alive,Pokhara-12,35000,Business Analyst,Bachelors,3.3
13,Puja Silwal,30,Female,1994-07-29,Alive,Lalitpur-02,50000,HR Manager,Masters,3.7
15,Anita Pandey,27,Female,1997-06-03,Alive,Butwal-03,28000,Data Analyst,Bachelors,3.4
16,Dipak Chaudhary,40,Male,1984-11-21,Alive,Biratnagar-07,65000,Senior Developer,Masters,3.8
17,Laxmi Bajracharya,31,Female,1993-04-16,Alive,Kathmandu-06,52000,Accountant,Bachelors,3.6
18,Nabin Dahal,24,Male,2000-09-27,Alive,Pokhara-11,21000,Intern,Running,3.0
19,Sabita Yadav,26,Female,1998-12-02,Alive,Lalitpur-09,27000,Junior Developer,Bachelors,3.5
20,Ram Sharma,25,Male,1999-01-15,Alive,Kathmandu-01,25000,Junior Developer,Bachelors,3.5
21,Sita Thapa,30,Female,1994-03-22,Alive,Pokhara-05,45000,Accountant,Bachelors,3.8

#### 9. Show all employees with Salary greater than 50000

In [59]:
df[df['Salary'] > 50000]

,Name,Age,Gender,DOB,DOD,Address,Salary,Post,Education,CGPA
2,Hari Prasad,45,Male,1979-07-10,2023-05-10,Chitwan-03,80000,Senior Manager,Masters,3.9
5,Maya Gurung,38,Female,1986-09-30,Alive,Kathmandu-10,60000,Project Manager,Masters,3.7
7,Rohan Magar,35,Male,1989-12-14,2021-08-15,Lalitpur-04,55000,Team Lead,Masters,3.8
10,Binod Adhikari,42,Male,1982-05-23,Alive,Biratnagar-11,70000,Senior Developer,Masters,3.9
14,Rajesh Koirala,50,Male,1974-01-08,2022-11-30,Chitwan-14,95000,Director,PhD,4.0
16,Dipak Chaudhary,40,Male,1984-11-21,Alive,Biratnagar-07,65000,Senior Developer,Masters,3.8
17,Laxmi Bajracharya,31,Female,1993-04-16,Alive,Kathmandu-06,52000,Accountant,Bachelors,3.6
22,Hari Prasad,45,Male,1979-07-10,2023-05-10,Chitwan-03,80000,Senior Manager,Masters,3.9

#### 10. Show all employees from Kathmandu

In [60]:
df[df['Address'].str.contains('Kathmandu')]

,Name,Age,Gender,DOB,DOD,Address,Salary,Post,Education,CGPA
0,Ram Sharma,25,Male,1999-01-15,Alive,Kathmandu-01,25000,Junior Developer,Bachelors,3.5
5,Maya Gurung,38,Female,1986-09-30,Alive,Kathmandu-10,60000,Project Manager,Masters,3.7
11,Kamala Poudel,33,Female,1991-10-11,Alive,Kathmandu-15,48000,Finance Manager,Masters,3.6
17,Laxmi Bajracharya,31,Female,1993-04-16,Alive,Kathmandu-06,52000,Accountant,Bachelors,3.6
20,Ram Sharma,25,Male,1999-01-15,Alive,Kathmandu-01,25000,Junior Developer,Bachelors,3.5

#### 11. Show all employees whose Education is Masters

In [61]:
df[df['Education'] == 'Masters']

,Name,Age,Gender,DOB,DOD,Address,Salary,Post,Education,CGPA
2,Hari Prasad,45,Male,1979-07-10,2023-05-10,Chitwan-03,80000,Senior Manager,Masters,3.9
5,Maya Gurung,38,Female,1986-09-30,Alive,Kathmandu-10,60000,Project Manager,Masters,3.7
7,Rohan Magar,35,Male,1989-12-14,2021-08-15,Lalitpur-04,55000,Team Lead,Masters,3.8
10,Binod Adhikari,42,Male,1982-05-23,Alive,Biratnagar-11,70000,Senior Developer,Masters,3.9
11,Kamala Poudel,33,Female,1991-10-11,Alive,Kathmandu-15,48000,Finance Manager,Masters,3.6
13,Puja Silwal,30,Female,1994-07-29,Alive,Lalitpur-02,50000,HR Manager,Masters,3.7
16,Dipak Chaudhary,40,Male,1984-11-21,Alive,Biratnagar-07,65000,Senior Developer,Masters,3.8
22,Hari Prasad,45,Male,1979-07-10,2023-05-10,Chitwan-03,80000,Senior Manager,Masters,3.9

#### 12. Show all employees with CGPA greater than 3.7

In [62]:
df[df['CGPA'] > 3.7]

,Name,Age,Gender,DOB,DOD,Address,Salary,Post,Education,CGPA
1,Sita Thapa,30,Female,1994-03-22,Alive,Pokhara-05,45000,Accountant,Bachelors,3.8
2,Hari Prasad,45,Male,1979-07-10,2023-05-10,Chitwan-03,80000,Senior Manager,Masters,3.9
7,Rohan Magar,35,Male,1989-12-14,2021-08-15,Lalitpur-04,55000,Team Lead,Masters,3.8
10,Binod Adhikari,42,Male,1982-05-23,Alive,Biratnagar-11,70000,Senior Developer,Masters,3.9
14,Rajesh Koirala,50,Male,1974-01-08,2022-11-30,Chitwan-14,95000,Director,PhD,4.0
16,Dipak Chaudhary,40,Male,1984-11-21,Alive,Biratnagar-07,65000,Senior Developer,Masters,3.8
21,Sita Thapa,30,Female,1994-03-22,Alive,Pokhara-05,45000,Accountant,Bachelors,3.8
22,Hari Prasad,45,Male,1979-07-10,2023-05-10,Chitwan-03,80000,Senior Manager,Masters,3.9

#### 13. Show all Female employees from Kathmandu

In [63]:
df[(df['Gender'] == 'Female') & df['Address'].str.contains('Kathmandu')]

,Name,Age,Gender,DOB,DOD,Address,Salary,Post,Education,CGPA
5,Maya Gurung,38,Female,1986-09-30,Alive,Kathmandu-10,60000,Project Manager,Masters,3.7
11,Kamala Poudel,33,Female,1991-10-11,Alive,Kathmandu-15,48000,Finance Manager,Masters,3.6
17,Laxmi Bajracharya,31,Female,1993-04-16,Alive,Kathmandu-06,52000,Accountant,Bachelors,3.6

#### 14. Show all employees with Salary between 30000 and 60000

In [64]:
df[df['Salary'].between(30000,60000)]

# df[(df['Salary'] > 30000) & (df['Salary'] < 60000) ]

,Name,Age,Gender,DOB,DOD,Address,Salary,Post,Education,CGPA
1,Sita Thapa,30,Female,1994-03-22,Alive,Pokhara-05,45000,Accountant,Bachelors,3.8
3,Gita Karki,28,Female,1996-11-05,Alive,Butwal-07,32000,HR Executive,Bachelors,3.6
5,Maya Gurung,38,Female,1986-09-30,Alive,Kathmandu-10,60000,Project Manager,Masters,3.7
6,Sunita Shrestha,27,Female,1997-04-25,Alive,Pokhara-08,30000,Data Analyst,Bachelors,3.4
7,Rohan Magar,35,Male,1989-12-14,2021-08-15,Lalitpur-04,55000,Team Lead,Masters,3.8
8,Priya Tamang,31,Female,1993-08-07,Alive,Chitwan-06,42000,Marketing Executive,Bachelors,3.5
11,Kamala Poudel,33,Female,1991-10-11,Alive,Kathmandu-15,48000,Finance Manager,Masters,3.6
12,Suresh Bhatt,29,Male,1995-03-17,Alive,Pokhara-12,35000,Business Analyst,Bachelors,3.3
13,Puja Silwal,30,Female,1994-07-29,Alive,Lalitpur-02,50000,HR Manager,Masters,3.7
17,Laxmi Bajracharya,31,Female,1993-04-16,Alive,Kathmandu-06,52000,Accountant,Bachelors,3.6
21,Sita Thapa,30,Female,1994-03-22,Alive,Pokhara-05,45000,Accountant,Bachelors,3.8

#### 15. Show the employee with the highest Salary

In [65]:
df[df['Salary'] == df['Salary'].max()]

,Name,Age,Gender,DOB,DOD,Address,Salary,Post,Education,CGPA
14,Rajesh Koirala,50,Male,1974-01-08,2022-11-30,Chitwan-14,95000,Director,PhD,4.0

#### 16. Show the employee with the lowest CGPA

In [66]:
df[df['CGPA'] == df['CGPA'].min()]

,Name,Age,Gender,DOB,DOD,Address,Salary,Post,Education,CGPA
18,Nabin Dahal,24,Male,2000-09-27,Alive,Pokhara-11,21000,Intern,Running,3.0

#### 17. Show all Male employees with Salary greater than 50000 AND CGPA greater than 3.7

In [67]:
df[(df['Gender']=='Male') & (df['Salary'] > 50000) & (df['CGPA'] > 3.7)]

,Name,Age,Gender,DOB,DOD,Address,Salary,Post,Education,CGPA
2,Hari Prasad,45,Male,1979-07-10,2023-05-10,Chitwan-03,80000,Senior Manager,Masters,3.9
7,Rohan Magar,35,Male,1989-12-14,2021-08-15,Lalitpur-04,55000,Team Lead,Masters,3.8
10,Binod Adhikari,42,Male,1982-05-23,Alive,Biratnagar-11,70000,Senior Developer,Masters,3.9
14,Rajesh Koirala,50,Male,1974-01-08,2022-11-30,Chitwan-14,95000,Director,PhD,4.0
16,Dipak Chaudhary,40,Male,1984-11-21,Alive,Biratnagar-07,65000,Senior Developer,Masters,3.8
22,Hari Prasad,45,Male,1979-07-10,2023-05-10,Chitwan-03,80000,Senior Manager,Masters,3.9

#### 18. Check if there are any duplicate rows

In [68]:
df.duplicated().any()

np.True_

#### 19. Show all duplicate rows

In [69]:
df[df.duplicated(keep = False)]

,Name,Age,Gender,DOB,DOD,Address,Salary,Post,Education,CGPA
0,Ram Sharma,25,Male,1999-01-15,Alive,Kathmandu-01,25000,Junior Developer,Bachelors,3.5
1,Sita Thapa,30,Female,1994-03-22,Alive,Pokhara-05,45000,Accountant,Bachelors,3.8
2,Hari Prasad,45,Male,1979-07-10,2023-05-10,Chitwan-03,80000,Senior Manager,Masters,3.9
20,Ram Sharma,25,Male,1999-01-15,Alive,Kathmandu-01,25000,Junior Developer,Bachelors,3.5
21,Sita Thapa,30,Female,1994-03-22,Alive,Pokhara-05,45000,Accountant,Bachelors,3.8
22,Hari Prasad,45,Male,1979-07-10,2023-05-10,Chitwan-03,80000,Senior Manager,Masters,3.9

#### 20. Count the total number of duplicate rows

In [70]:
df.duplicated().sum()

np.int64(3)

#### 21. Drop duplicate rows keeping the first occurrence

In [71]:
df.drop_duplicates(keep='first')

,Name,Age,Gender,DOB,DOD,Address,Salary,Post,Education,CGPA
0,Ram Sharma,25,Male,1999-01-15,Alive,Kathmandu-01,25000,Junior Developer,Bachelors,3.5
1,Sita Thapa,30,Female,1994-03-22,Alive,Pokhara-05,45000,Accountant,Bachelors,3.8
2,Hari Prasad,45,Male,1979-07-10,2023-05-10,Chitwan-03,80000,Senior Manager,Masters,3.9
3,Gita Karki,28,Female,1996-11-05,Alive,Butwal-07,32000,HR Executive,Bachelors,3.6
4,Bishnu Rai,22,Male,2002-06-18,Alive,Biratnagar-02,20000,Intern,Running,3.2
5,Maya Gurung,38,Female,1986-09-30,Alive,Kathmandu-10,60000,Project Manager,Masters,3.7
6,Sunita Shrestha,27,Female,1997-04-25,Alive,Pokhara-08,30000,Data Analyst,Bachelors,3.4
7,Rohan Magar,35,Male,1989-12-14,2021-08-15,Lalitpur-04,55000,Team Lead,Masters,3.8
8,Priya Tamang,31,Female,1993-08-07,Alive,Chitwan-06,42000,Marketing Executive,Bachelors,3.5
9,Anil Basnet,24,Male,2000-02-19,Alive,Butwal-09,22000,Junior Developer,Running,3.1
10,Binod Adhikari,42,Male,1982-05-23,Alive,Biratnagar-11,70000,Senior Developer,Masters,3.9
11,Kamala Poudel,33,Female,1991-10-11,Alive,Kathmandu-15,48000,Finance Manager,Masters,3.6
12,Suresh Bhatt,29,Male,1995-03-17,Alive,Pokhara-12,35000,Business Analyst,Bachelors,3.3
13,Puja Silwal,30,Female,1994-07-29,Alive,Lalitpur-02,50000,HR Manager,Masters,3.7
14,Rajesh Koirala,50,Male,1974-01-08,2022-11-30,Chitwan-14,95000,Director,PhD,4.0
15,Anita Pandey,27,Female,1997-06-03,Alive,Butwal-03,28000,Data Analyst,Bachelors,3.4
16,Dipak Chaudhary,40,Male,1984-11-21,Alive,Biratnagar-07,65000,Senior Developer,Masters,3.8
17,Laxmi Bajracharya,31,Female,1993-04-16,Alive,Kathmandu-06,52000,Accountant,Bachelors,3.6
18,Nabin Dahal,24,Male,2000-09-27,Alive,Pokhara-11,21000,Intern,Running,3.0
19,Sabita Yadav,26,Female,1998-12-02,Alive,Lalitpur-09,27000,Junior Developer,Bachelors,3.5

#### 22. Drop duplicate rows keeping the last occurrence

In [73]:
df.drop_duplicates(keep = 'last')

,Name,Age,Gender,DOB,DOD,Address,Salary,Post,Education,CGPA
3,Gita Karki,28,Female,1996-11-05,Alive,Butwal-07,32000,HR Executive,Bachelors,3.6
4,Bishnu Rai,22,Male,2002-06-18,Alive,Biratnagar-02,20000,Intern,Running,3.2
5,Maya Gurung,38,Female,1986-09-30,Alive,Kathmandu-10,60000,Project Manager,Masters,3.7
6,Sunita Shrestha,27,Female,1997-04-25,Alive,Pokhara-08,30000,Data Analyst,Bachelors,3.4
7,Rohan Magar,35,Male,1989-12-14,2021-08-15,Lalitpur-04,55000,Team Lead,Masters,3.8
8,Priya Tamang,31,Female,1993-08-07,Alive,Chitwan-06,42000,Marketing Executive,Bachelors,3.5
9,Anil Basnet,24,Male,2000-02-19,Alive,Butwal-09,22000,Junior Developer,Running,3.1
10,Binod Adhikari,42,Male,1982-05-23,Alive,Biratnagar-11,70000,Senior Developer,Masters,3.9
11,Kamala Poudel,33,Female,1991-10-11,Alive,Kathmandu-15,48000,Finance Manager,Masters,3.6
12,Suresh Bhatt,29,Male,1995-03-17,Alive,Pokhara-12,35000,Business Analyst,Bachelors,3.3
13,Puja Silwal,30,Female,1994-07-29,Alive,Lalitpur-02,50000,HR Manager,Masters,3.7
14,Rajesh Koirala,50,Male,1974-01-08,2022-11-30,Chitwan-14,95000,Director,PhD,4.0
15,Anita Pandey,27,Female,1997-06-03,Alive,Butwal-03,28000,Data Analyst,Bachelors,3.4
16,Dipak Chaudhary,40,Male,1984-11-21,Alive,Biratnagar-07,65000,Senior Developer,Masters,3.8
17,Laxmi Bajracharya,31,Female,1993-04-16,Alive,Kathmandu-06,52000,Accountant,Bachelors,3.6
18,Nabin Dahal,24,Male,2000-09-27,Alive,Pokhara-11,21000,Intern,Running,3.0
19,Sabita Yadav,26,Female,1998-12-02,Alive,Lalitpur-09,27000,Junior Developer,Bachelors,3.5
20,Ram Sharma,25,Male,1999-01-15,Alive,Kathmandu-01,25000,Junior Developer,Bachelors,3.5
21,Sita Thapa,30,Female,1994-03-22,Alive,Pokhara-05,45000,Accountant,Bachelors,3.8
22,Hari Prasad,45,Male,1979-07-10,2023-05-10,Chitwan-03,80000,Senior Manager,Masters,3.9

#### 23. Drop duplicates based on Name column only

In [78]:
df.drop_duplicates(subset = ['Name'], keep = 'first')

,Name,Age,Gender,DOB,DOD,Address,Salary,Post,Education,CGPA
0,Ram Sharma,25,Male,1999-01-15,Alive,Kathmandu-01,25000,Junior Developer,Bachelors,3.5
1,Sita Thapa,30,Female,1994-03-22,Alive,Pokhara-05,45000,Accountant,Bachelors,3.8
2,Hari Prasad,45,Male,1979-07-10,2023-05-10,Chitwan-03,80000,Senior Manager,Masters,3.9
3,Gita Karki,28,Female,1996-11-05,Alive,Butwal-07,32000,HR Executive,Bachelors,3.6
4,Bishnu Rai,22,Male,2002-06-18,Alive,Biratnagar-02,20000,Intern,Running,3.2
5,Maya Gurung,38,Female,1986-09-30,Alive,Kathmandu-10,60000,Project Manager,Masters,3.7
6,Sunita Shrestha,27,Female,1997-04-25,Alive,Pokhara-08,30000,Data Analyst,Bachelors,3.4
7,Rohan Magar,35,Male,1989-12-14,2021-08-15,Lalitpur-04,55000,Team Lead,Masters,3.8
8,Priya Tamang,31,Female,1993-08-07,Alive,Chitwan-06,42000,Marketing Executive,Bachelors,3.5
9,Anil Basnet,24,Male,2000-02-19,Alive,Butwal-09,22000,Junior Developer,Running,3.1
10,Binod Adhikari,42,Male,1982-05-23,Alive,Biratnagar-11,70000,Senior Developer,Masters,3.9
11,Kamala Poudel,33,Female,1991-10-11,Alive,Kathmandu-15,48000,Finance Manager,Masters,3.6
12,Suresh Bhatt,29,Male,1995-03-17,Alive,Pokhara-12,35000,Business Analyst,Bachelors,3.3
13,Puja Silwal,30,Female,1994-07-29,Alive,Lalitpur-02,50000,HR Manager,Masters,3.7
14,Rajesh Koirala,50,Male,1974-01-08,2022-11-30,Chitwan-14,95000,Director,PhD,4.0
15,Anita Pandey,27,Female,1997-06-03,Alive,Butwal-03,28000,Data Analyst,Bachelors,3.4
16,Dipak Chaudhary,40,Male,1984-11-21,Alive,Biratnagar-07,65000,Senior Developer,Masters,3.8
17,Laxmi Bajracharya,31,Female,1993-04-16,Alive,Kathmandu-06,52000,Accountant,Bachelors,3.6
18,Nabin Dahal,24,Male,2000-09-27,Alive,Pokhara-11,21000,Intern,Running,3.0
19,Sabita Yadav,26,Female,1998-12-02,Alive,Lalitpur-09,27000,Junior Developer,Bachelors,3.5

#### 24. Check duplicates based on Post and Education columns

In [85]:
df.duplicated(subset = ['Post','Education']).sum()

np.int64(8)

In [89]:
df[df.duplicated(subset = ['Post','Education'],keep = 'first')]

,Name,Age,Gender,DOB,DOD,Address,Salary,Post,Education,CGPA
15,Anita Pandey,27,Female,1997-06-03,Alive,Butwal-03,28000,Data Analyst,Bachelors,3.4
16,Dipak Chaudhary,40,Male,1984-11-21,Alive,Biratnagar-07,65000,Senior Developer,Masters,3.8
17,Laxmi Bajracharya,31,Female,1993-04-16,Alive,Kathmandu-06,52000,Accountant,Bachelors,3.6
18,Nabin Dahal,24,Male,2000-09-27,Alive,Pokhara-11,21000,Intern,Running,3.0
19,Sabita Yadav,26,Female,1998-12-02,Alive,Lalitpur-09,27000,Junior Developer,Bachelors,3.5
20,Ram Sharma,25,Male,1999-01-15,Alive,Kathmandu-01,25000,Junior Developer,Bachelors,3.5
21,Sita Thapa,30,Female,1994-03-22,Alive,Pokhara-05,45000,Accountant,Bachelors,3.8
22,Hari Prasad,45,Male,1979-07-10,2023-05-10,Chitwan-03,80000,Senior Manager,Masters,3.9